// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CubeClicker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.Serialization;
    
    
    public partial class GameStartCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class ClickCubeCommand : uFrame.MVVM.ViewModelCommand {
    }
    
    public partial class ExpireCubeCommand : uFrame.MVVM.ViewModelCommand {
    }
}
