// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CubeClicker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.IOC;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.Serialization;
    
    
    public class TitleSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "ProjectRepositoryKernelScene";
            }
        }
        
        public virtual TitleSceneSettings Settings {
            get {
                return _SettingsObject as TitleSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class TitleSceneLoaderBase : SceneLoader<TitleScene> {
        
        protected override IEnumerator LoadScene(TitleScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(TitleScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
    
    public class MainSceneBase : uFrame.Kernel.Scene {
        
        public override string DefaultKernelScene {
            get {
                return "ProjectRepositoryKernelScene";
            }
        }
        
        public virtual MainSceneSettings Settings {
            get {
                return _SettingsObject as MainSceneSettings;
            }
            set {
                _SettingsObject = value;
            }
        }
    }
    
    public class MainSceneLoaderBase : SceneLoader<MainScene> {
        
        protected override IEnumerator LoadScene(MainScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
        
        protected override IEnumerator UnloadScene(MainScene scene, Action<float, string> progressDelegate) {
            yield break;
        }
    }
}
