// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CubeClicker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using CubeClicker;
    using uFrame.IOC;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    using uFrame.MVVM;
    
    
    public class GameCoreServiceBase : uFrame.Kernel.SystemServiceMonoBehavior {
        
        /// <summary>
        /// This method is invoked whenever the kernel is loading.
        /// Since the kernel lives throughout the entire lifecycle of the game, this will only be invoked once.
        /// </summary>
        public override void Setup() {
            base.Setup();
            this.OnEvent<GameStartEvent>().Subscribe(this.GameStartEventHandler);
            this.OnEvent<ClickCubeEvent>().Subscribe(this.ClickCubeEventHandler);
            this.OnEvent<ExpireCubeEvent>().Subscribe(this.ExpireCubeEventHandler);
            this.OnEvent<GameEndEvent>().Subscribe(this.GameEndEventHandler);
        }
        
        /// <summary>
        // This method is executed when using this.Publish(new GameStartEvent())
        /// </summary>
        public virtual void GameStartEventHandler(GameStartEvent data) {
            // Process the commands information.  Also, you can publish new events by using the line below.
            // this.Publish(new AnotherEvent())
        }
        
        /// <summary>
        // This method is executed when using this.Publish(new ClickCubeEvent())
        /// </summary>
        public virtual void ClickCubeEventHandler(ClickCubeEvent data) {
            // Process the commands information.  Also, you can publish new events by using the line below.
            // this.Publish(new AnotherEvent())
        }
        
        /// <summary>
        // This method is executed when using this.Publish(new ExpireCubeEvent())
        /// </summary>
        public virtual void ExpireCubeEventHandler(ExpireCubeEvent data) {
            // Process the commands information.  Also, you can publish new events by using the line below.
            // this.Publish(new AnotherEvent())
        }
        
        /// <summary>
        // This method is executed when using this.Publish(new GameEndEvent())
        /// </summary>
        public virtual void GameEndEventHandler(GameEndEvent data) {
            // Process the commands information.  Also, you can publish new events by using the line below.
            // this.Publish(new AnotherEvent())
        }
    }
}
