// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CubeClicker {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.MVVM;
    using uFrame.MVVM.Bindings;
    using uFrame.Serialization;
    using CubeClicker;
    
    
    public class GameStartEventBase : object {
    }
    
    public class ClickCubeEventBase : object {
        
        private CubeViewModel _Target;
        
        public CubeViewModel Target {
            get {
                return _Target;
            }
            set {
                _Target = value;
            }
        }
    }
    
    public class ExpireCubeEventBase : object {
        
        private CubeViewModel _Target;
        
        public CubeViewModel Target {
            get {
                return _Target;
            }
            set {
                _Target = value;
            }
        }
    }
    
    public class GameEndEventBase : object {
    }
}
